### ISSUE TITLE
feat: automated package building and release workflows

### ISSUE THREAD

**Issue by pierre-warnier** [butterfly-osm/butterfly-dl#14]
## Summary

Implement automated package building and release workflows using GitHub Actions to streamline the release process and provide pre-built binaries for users.

## Background

Currently, users must build from source using `cargo build --release`. We should provide:
- Pre-built binaries for major platforms
- Automated releases triggered by version tags
- Package artifacts for distribution

### 🚀 **Automated Release Workflow**
- **Trigger**: On git tag push (e.g., `v1.4.2`)
- **Cross-platform builds**: Linux (x86_64, ARM64), macOS (Intel, Apple Silicon), Windows
- **Release artifacts**: Static binaries, checksums, signatures
- **Changelog**: Auto-generated from conventional commits

### 📦 **Package Building**
- **Static linking**: Self-contained binaries with minimal dependencies
- **Optimization**: Release builds with size and performance optimization
- **Validation**: Automated testing of built artifacts
- **Checksums**: SHA256 hashes for integrity verification

### 🏗️ **CI/CD Integration**
- **Build matrix**: Multiple Rust targets and platforms
- **Testing**: Run full test suite before release
- **Artifact upload**: Attach binaries to GitHub releases
- **Version synchronization**: Ensure VERSION file and Cargo.toml alignment

### GitHub Actions Workflows

1. **Release Workflow** (`.github/workflows/release.yml`)
   ```yaml
   name: Release
   on:
     push:
       tags: ['v*']
   jobs:
     build:
       strategy:
         matrix:
           include:
             - target: x86_64-unknown-linux-gnu
             - target: aarch64-unknown-linux-gnu  
             - target: x86_64-apple-darwin
             - target: aarch64-apple-darwin
             - target: x86_64-pc-windows-msvc
   ```

2. **Build Matrix Targets**
   - `x86_64-unknown-linux-gnu` (Linux Intel/AMD)
   - `aarch64-unknown-linux-gnu` (Linux ARM64)
   - `x86_64-apple-darwin` (macOS Intel)
   - `aarch64-apple-darwin` (macOS Apple Silicon)
   - `x86_64-pc-windows-msvc` (Windows)

3. **Release Assets**
   - `butterfly-dl-v1.4.2-x86_64-linux.tar.gz`
   - `butterfly-dl-v1.4.2-aarch64-linux.tar.gz`
   - `butterfly-dl-v1.4.2-x86_64-macos.tar.gz`
   - `butterfly-dl-v1.4.2-aarch64-macos.tar.gz`
   - `butterfly-dl-v1.4.2-x86_64-windows.zip`
   - `checksums.txt` (SHA256 hashes)

### 👥 **User Experience**
- **Easy installation**: Download and run, no compilation required
- **Multiple platforms**: Support for all major operating systems
- **Consistent releases**: Automated, reliable release process
- **Security**: Verified checksums and signatures

### 🔧 **Developer Experience**  
- **Streamlined releases**: Tag-based automatic releases
- **Quality assurance**: Automated testing before release
- **Documentation**: Auto-generated changelogs
- **Maintenance**: Reduced manual release work

## Acceptance Criteria

- [ ] GitHub Actions workflow for cross-platform builds
- [ ] Automated release creation on version tags
- [ ] Pre-built binaries for Linux, macOS, Windows (x86_64 + ARM64)
- [ ] SHA256 checksums for all release artifacts
- [ ] Integration with existing VERSION file system
- [ ] Documentation for release process in CONTRIBUTING.md
- [ ] Test release workflow with a patch version

## Related

- Current version management system (VERSION file + build.rs)
- Existing Cargo.toml configuration
- Cross-compilation requirements for Rust + C dependencies

## Priority

**High** - This significantly improves user onboarding and reduces friction for adoption.

---

**Labels:** `enhancement`, `ci/cd`, `release`, `automation`
